# docker-compose.yml - Database services cho agents

services:
  # PostgreSQL cho metadata storage
  postgres:
    image: postgres:15
    container_name: ai_challenge_postgres
    environment:
      POSTGRES_DB: ai_challenge
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - ai_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_challenge"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis cho caching và session storage
  redis:
    image: redis:7-alpine
    container_name: ai_challenge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ai_network
    restart: unless-stopped

  # Neo4j cho knowledge graph
  neo4j:
    image: neo4j:5
    container_name: ai_challenge_neo4j
    environment:
      NEO4J_AUTH: neo4j/ai_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports:
      - "7474:7474"  # Web interface
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - ai_network
    restart: unless-stopped

  # Elasticsearch cho full-text search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ai_challenge_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - ai_network
    restart: unless-stopped

  # Minio cho object storage
  minio:
    image: minio/minio:latest
    container_name: ai_challenge_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ai_network
    restart: unless-stopped

  # Grafana cho monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: ai_challenge_grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ai_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  neo4j_logs:
  es_data:
  minio_data:
  grafana_data:

networks:
  ai_network:
    driver: bridge