apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: ai-challenge
spec:
  ports:
  - port: 7687
    targetPort: 7687
    name: bolt
  - port: 7474
    targetPort: 7474
    name: http
  selector:
    app: neo4j
  type: ClusterIP